### ISSUE TITLE
[Testing Help/Bug] Testing Issues Discussion

### ISSUE THREAD

**Issue by andrewleow97** [AY1920S1-CS2113T-F10-1/main#124]
Hey everyone need some help with the JUnit testing

Currently trying to create a new test class to test user input, so I extend the InputTest class and utilise its methods, but when running NoSuchElementException is thrown with the message "No line found."

This does not occur with the "bye" user input, not sure if its something to do with the arguments required

Would appreciate if anyone can help with this T.T
![image](https://user-images.githubusercontent.com/42372438/67824661-ffffbd00-fb01-11e9-954e-d2b11e25efb7.png)

**Comment by namiwa** [comment]
Try to remove the `restoreStream` and `setupStream` function call, since the `@AfterAll` tags forces it to be run after each test case called under the `InputTest` class

**Comment by andrewleow97** [comment]
Seems only "bye" command is working right now, have tried with our other commands (e.g add, remove, show, sort). Might have something to do with the spaces in the command since "bye" is our only single word command.

**Comment by namiwa** [comment]
okay, ill go take a look then test with multi-spaced commands

**Comment by andrewleow97** [comment]
> Try to remove the `restoreStream` and `setupStream` function call, since the `@AfterAll` and `@BeforeAll` tags sets up each call before and after each test cases under the `InputTest` class.

Did the above, same issue :'(

> This is more of integration testing, though I think for unit test you can directly create dummy Command classes and test them directly
True but I think it's still important to test user inputs as well, in case some special case user input comes up.

**Comment by namiwa** [comment]
@andrewleow97 and in this case, nice bug find! Turns out the error is due to calling `nextLine` for the `Scanner` object, and failling to check for a valid next line D:

![Scanner Bug](https://user-images.githubusercontent.com/42546125/67827100-b9ae5c00-fb09-11e9-83f9-5e9ce1672502.png)

I will make a pr resolving the scanner issue, but this forces us to our format to test to always include a bye command to ensure that the scanner is always closed to prevent infinite loop during testing. For the time being, would that be a good compromise?

**Comment by andrewleow97** [comment]
> I will make a pr resolving the scanner issue, but this forces us to our format to test to always include a bye command to ensure that the scanner is always closed to prevent infinite loop during testing. For the time being, would that be a good compromise?

I think this compromise fine, good work Iman!!

**Comment by namiwa** [comment]
@andrewleow97 @LongLeCE @kyawtsan99 @e0313687 note that the following applies to testing using another class which inherits from `InputTest` (See `ShowTest` for sample example)

1. For the user input to be tested, ensure that the string contains both the command to be tested, plus the next line character and finally the `bye` string. Ensure that the entire string command to be tested is passed into the `provideInput` method: 

![image](https://user-images.githubusercontent.com/42546125/67946221-d1760500-fc1b-11e9-92e3-2a173df16aba.png)

2. Ensure that a `String[]` array is created and passed into the `main` method found in `CliLauncher`

![image](https://user-images.githubusercontent.com/42546125/67946340-1f8b0880-fc1c-11e9-9c5a-6a35121992e1.png)

3. Create an expected string, which contains the expected output to be displayed. Below contains example for testing the `bye` command

![image](https://user-images.githubusercontent.com/42546125/67946434-5fea8680-fc1c-11e9-95b4-1536bbd5ebde.png)

4. Compare the expected against the console output captured by `outContent`. To ensure compatibility with Windows terminal, the unprintable `\r` character must be replaced with an empty string to ensure that the output can be compared correctly.

![image](https://user-images.githubusercontent.com/42546125/67946609-a7711280-fc1c-11e9-87d0-d82215439815.png)

**Comment by namiwa** [comment]
Tested for v1.4

**Comment by namiwa** [comment]
@andrewleow97, @e0313687, @kyawtsan99 
Update for integration testing as of v1.4, after the password feature has been implemented by @LongLeCE, all testing cases using `CliLauncher.main()` requires that `provideInput()` has the password string as `"password\n"` before the command being tested following the bye command.

**Comment by namiwa** [comment]
![image](https://user-images.githubusercontent.com/42546125/68546819-d6a23380-0415-11ea-84d2-287e28bd1a1e.png)

@andrewleow97  @LongLeCE @e0313687 @kyawtsan99 
I have temporarily removed the checking for the test class above as there are cases where the method given gives passing test cases locally in Intellij and Gradle but fails on Travis CI. Will try to look into this behavior by Monday.

![image](https://user-images.githubusercontent.com/42546125/68546891-968f8080-0416-11ea-93bc-7b70142d6d5b.png)

![image](https://user-images.githubusercontent.com/42546125/68546859-38629d80-0416-11ea-9264-dd0953a41f9f.png)

**Comment by andrewleow97** [comment]
Completed v1.4 testing
