### ISSUE TITLE
Module able to be added more than once

### ISSUE THREAD

**Issue by namiwa** [AY1920S1-CS2113T-F10-1/main#213]
![image](https://user-images.githubusercontent.com/42546125/68532329-dd1da600-0356-11ea-8f45-9bd6bf49590a.png)

After grading the module, adding the same module again skips the duplicate checks. Could this be verified?

**Comment by LongLeCE** [comment]
Just checked the clashing logic of module.
I can confirm that current logic allows this bug to happen.

**Comment by LongLeCE** [comment]
Fixed in #214
