### ISSUE TITLE
[Bug] - Program crashes with adding CCA

### ISSUE THREAD

**Issue by namiwa** [AY1920S1-CS2113T-F10-1/main#218]
As found by @kyawtsan99, this crashing behavior is verified as of the current build. Could we look into this by tomorrow?

![image](https://user-images.githubusercontent.com/42546125/68542061-df2d4680-03e2-11ea-8ccf-29b4019beaa3.png)

**Comment by LongLeCE** [comment]
I could not reproduce it at all
Did you merge the latest code before trying the command?
x-special/nautilus-clipboard
copy
file:///home/longlh/Pictures/Screenshot%20from%202019-11-10%2022-42-08.png

**Comment by namiwa** [comment]
@LongLeCE you're right, the behavior was such as I did not delete the existing user profile file
@e0313687 @andrewleow97 @kyawtsan99 note that for testing we would have to remove the password portion for tests using InputTest as the update in #124 no longer applies.

**Comment by namiwa** [comment]
Closed as bug no longer affects.
