### ISSUE TITLE
[Bug] - Reminder Thread fails during run

### ISSUE THREAD

**Issue by namiwa** [AY1920S1-CS2113T-F10-1/main#73]
![image](https://user-images.githubusercontent.com/42546125/66505162-5a0df380-eafd-11e9-8436-06830b16df0b.png)

@LongLeCE the reminder thread still fails with this stack trace, maybe for this upcoming milestone we implement other features first before fixing this?

**Comment by namiwa** [comment]
As discussed, the thread issue occurs when the terminate command is input by the user

**Comment by LongLeCE** [comment]
Fixed in pr #78

**Comment by namiwa** [comment]
Looks good, will close this issue!
